# Update <REGISTRY> <NAMESPACE> values before use
apiVersion: apps/v1
kind: Deployment
metadata:
  name: on-school
  labels:
    app: on-school
spec:
  replicas: 1
  selector:
    matchLabels:
      app: on-school
  template:
    metadata:
      labels:
        app: on-school
    spec:
      containers:
      - name: on-school
        image: <REGISTRY>/<NAMESPACE>/myapp:v1.0.0
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
        env:
        - name: CLOUDANT_URL
          valueFrom:
            secretKeyRef:
              name: cloudant
              key: url
              optional: true

